-----
# **Context**
-----

**WOW Superstore** sells different products like office supplies, furniture and appliances. For each order that is placed, the superstore keeps a record of various attributes related to the product, like state, city, category, subcategory and quantity.

**Let's display a welcome message from WOW Superstore.**

* We can use the print() function for this purpose.

In [ ]:
message = "Hi! Welcome to WOW Superstore."
print(message)

* In the above cell, 'message' is a **variable**.

* Variables can store data of different types.

* Variables in Python can have different data types.

* 'message' above is of string (str) type.

**The superstore has a stock of 100 phones. Recently, an order was placed for 20 phones. It has to be updated to add 10 more phones.**

In [ ]:
order_init = 20
print('Initial order:', order_init)

order_upd = order_init + 10
print('Updated order:', order_upd)

* 'order_init' and 'order_upd' above are of integer (int) type.

**The inventory has to be updated as per the updated order. We will have to subtract the quantity of phones in the updated order (order_upd) from the initial inventory count of 100.**

In [ ]:
inventory_init = 100
print('Initial Inventory:', inventory_init)

inventory_upd = inventory_in - order_upd
print('Updated Inventory:', inventory_upd)

* Something went wrong as we got an error.
* The error is raised as we have misspelled the variable name.
* Let's correct the error and run the code again.

In [ ]:
inventory_init = 100
print('Initial Inventory:', inventory_init)

inventory_upd = inventory_init - 30
print('Updated Inventory:', inventory_upd)

**The cost of each phone is $150.50. Let's compute the total amount for the updated order (order_upd).**

In [ ]:
quantity = 30
unit_price = 150.50

total_amnt = quantity*unit_price

Print('Total Order Amount:', total_amnt)

* We have encountered an error again.
* The error is raised as we have misspelled the function name.
* Python is case-sensitive. So, print() and Print() are different functions.
* Let's correct the code and run it again.

In [ ]:
quantity = 30
unit_price = 150.50

total_amnt = quantity*unit_price

print('Total Order Amount:', total_amnt)

* 'unit_price' and 'total_amnt' above are of float type.

**For the upcoming Black Friday sale, the superstore is providing a discount of 20% on phones and 10% on chairs, but there is no discount on any other product.**

**For a given product, let's display a message that informs a customer about how much discount they will get on their order.**

In [ ]:
product = input('Enter the product: ')

if product == 'phone':
    print('You will receive a 20% discount on this product!!')
elif product == 'chair':
    print('You will receive a 10% discount on this product!!')
else:
    print('Sorry! There is no discount on this product.')

**WOW Superstore has provided a snapshot of some of the product attributes stored by them.**

| Order ID | Category | Sub-Category | Quantity | Unit Price |
| --- | --- | --- | --- | --- | 
| WOWORD001 | Office Supplies | Binders | 3 | 10.20 |
| WOWORD002 | Technology | Phones | 30 | 150.50 |
| WOWORD003 | Office Supplies | Paper | 50 | 4.50 |
| WOWORD004 | Furniture | Chairs | 5 | 30.75 |
| WOWORD005 | Office Supplies | Binders | 2 | 10.20 |

**Let's create a variable that will store all the order IDs.**

In [ ]:
order_id = "WOWORD001"
order_id = "WOWORD002"
order_id = "WOWORD003"
order_id = "WOWORD004"
order_id = "WOWORD005"

print("Order IDs: ", order_id)

* That didn't work! The value of the variable got updated at each step.
* How do we store all the values in one variable?
* We will have to create a 'list' of values.

In [ ]:
order_id_list = ["WOWORD001", "WOWORD002", "WOWORD003", "WOWORD004"]

# let's print the list we just created
print('Order IDs:', order_id_list)

* That seems to have worked.
* But we missed one order ID.
* Will we have to recreate the list from scratch?
* NO! We can add the missed order ID to the current list using the *append()* function.

In [ ]:
order_id_list.append("WOWORD005")
print('Order IDs:', order_id_list)

* The list of order IDs is fixed now.
* Let's create lists for the other attributes too.

In [ ]:
category_list = ['Office Supplies', 'Technology', 'Office Supplies', 'Furniture', 'Office Supplies']
sub_category_list = ['Binders', 'Phones', 'Paper', 'Chairs', 'Binders']
quantity_list =[3, 30, 50, 5, 2]
unit_price_list = [10.20, 150.50, 4.50, 30.75, 10.20]

In [ ]:
# let's print the lists we created
print('Category List:',category_list)
print('Sub-Category List:',sub_category_list)
print('Quantity List:',quantity_list)
print('Unit Price List:',unit_price_list)

* If we want to analyze this data, we will have to work with multiple lists. 
* It will not be feasible to apply different operations on multiple lists, especially if the number of attributes increases.
* So, it is clear we need a more efficient way of handling the data simultaneously at the attribute and record levels.
* In Python, we can do this with pandas dataframe.

* pandas is a powerful, easy-to-use, open-source Python library used for data analysis and manipulation.
* It is very useful when working with tabular data.
* Python has many other libraries which are useful for different tasks.
* We can import these libraries into a Jupyter notebook to access and use the functionalities of these libraries.

**Let's combine the lists we created into a dataframe. To do that, we have to first import the pandas library.**

In [ ]:
# importing the pandas library
import pandas as pd

* Let's first create an empty dataframe.

In [ ]:
superstore_data = pd.DataFrame()

* Next, we will add one column to the empty dataframe.

*Let's see what all we have in the **order_id_list** first-*

In [ ]:
print(order_id_list)

*now, we will be creating the 'OrderId' column using the values of the order_id list -*

In [ ]:
superstore_data['OrderId'] = order_id_list

In [ ]:
# displaying the dataframe
superstore_data

 * Similarly, let's add the other columns using the list that has been created.

In [ ]:
superstore_data['Category'] = category_list
superstore_data['Sub_Category'] = sub_category_list
superstore_data['Quantity'] = quantity_list
superstore_data['Unit Price'] = unit_price_list

In [ ]:
# displaying the dataframe
superstore_data

**Let's create another column 'Total_Amount' in the dataframe that will contain the product of quantity and unit price.**

In [ ]:
superstore_data['Total_Amount'] = superstore_data['Quantity'] * superstore_data['Unit Price']
superstore_data

* We have created the Total_Amount column successfully.

**The superstore is currently not shipping office supplies due to COVID restrictions.**

**We have to print an appropriate message for the customer depending upon the category of the product ordered.**

In [ ]:
for i in superstore_data['Category']:
  print('Product Ordered:', i)
  if i == 'Office Supplies':
    print('Sorry! The product is currently not being shipped.\n')
  else:
    print('Your order will be shipped at the earliest.\n')

* What we saw above was just a snapshot of data.
* The complete data has a lot more columns and observations.
* It is clear that it will not be feasible to analyze the complete data by creating a dataframe from multiple lists.

* We generally have tabular data stored as CSV or Excel files.
* They can be loaded directly into a pandas dataframe.
* The WOW Superstore data is available in a CSV format.
* We can load the data into a pandas dataframe using the *read_csv()* function.

**Loading a dataset in colab:**

To load a dataset in colab, we need to give 'google colab' the access to our google drive -

In [ ]:
# Mounting google drive to access files
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# loading the data file into a pandas dataframe
data = pd.read_csv('/content/WOW_Superstore.csv')

**Let's take a quick look at the data.**

In [ ]:
# viewing the first 5 rows of the data
data.head()

In [ ]:
# viewing the last 5 rows of the data
data.tail()